export const CATEGORIES = [
    'Housing',
    'Utilities',
    'Food & Dining',
    'Transportation',
    'Entertainment',
    'Health & Fitness',
    'Shopping',
    'Insurance',
    'Personal Care',
    'Education',
    'Subscriptions',
    'Investments',
    'Debt & Loans',
    'Credit Card',
    'Student Loan',
    'Gifts & Donations',
    'Taxes',
    'Travel',
    'Pets',
    'Other',
    'Custom'
];

export const CATEGORY_ICONS: Record<string, string> = {
    'Housing': 'home',
    'Utilities': 'flash',
    'Food & Dining': 'silverware-fork-knife',
    'Transportation': 'car',
    'Entertainment': 'movie',
    'Health & Fitness': 'heart-pulse',
    'Shopping': 'shopping',
    'Insurance': 'shield-check',
    'Personal Care': 'face-man',
    'Education': 'school',
    'Subscriptions': 'calendar-refresh',
    'Investments': 'trending-up',
    'Debt & Loans': 'bank',
    'Credit Card': 'credit-card',
    'Student Loan': 'school',
    'Gifts & Donations': 'gift',
    'Taxes': 'file-document-outline',
    'Travel': 'airplane',
    'Pets': 'paw',
    'Other': 'dots-horizontal',
    'Custom': 'star'
};
